package com.hackhub.api.exception;

import jakarta.servlet.http.HttpServletRequest;
import java.time.Instant;
import java.util.List;
import java.util.stream.Collectors;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.core.AuthenticationException;
import org.springframework.validation.BindException;
import org.springframework.validation.FieldError;
import org.springframework.web.servlet.NoHandlerFoundException;
import org.springframework.web.servlet.resource.NoResourceFoundException;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Global exception handler for the HackHub REST API.
 *
 * <p>This component centralizes exception handling across all controllers
 * and converts application exceptions into consistent HTTP error responses
 * represented by {@link ApiError}.</p>
 *
 * <p>The handler maps domain, validation, authentication, authorization,
 * routing, and unexpected exceptions to appropriate HTTP status codes,
 * ensuring a uniform error response format throughout the application.</p>
 */
@RestControllerAdvice
public class GlobalExceptionHandler {

	/**
	 * Handles resource-not-found exceptions.
	 *
	 * @param ex the thrown exception
	 * @param request the current HTTP request
	 * @return a 404 Not Found response
	 */
	@ExceptionHandler(NotFoundException.class)
	public ResponseEntity<ApiError> handleNotFound(NotFoundException ex, HttpServletRequest request) {
		return buildResponse(HttpStatus.NOT_FOUND, ex.getMessage(), request, List.of());
	}

	/**
	 * Handles forbidden operation exceptions.
	 *
	 * @param ex the thrown exception
	 * @param request the current HTTP request
	 * @return a 403 Forbidden response
	 */
	@ExceptionHandler(ForbiddenException.class)
	public ResponseEntity<ApiError> handleForbidden(ForbiddenException ex, HttpServletRequest request) {
		return buildResponse(HttpStatus.FORBIDDEN, ex.getMessage(), request, List.of());
	}

	/**
	 * Handles invalid client request exceptions.
	 *
	 * @param ex the thrown exception
	 * @param request the current HTTP request
	 * @return a 400 Bad Request response
	 */
	@ExceptionHandler(BadRequestException.class)
	public ResponseEntity<ApiError> handleBadRequest(BadRequestException ex, HttpServletRequest request) {
		return buildResponse(HttpStatus.BAD_REQUEST, ex.getMessage(), request, List.of());
	}

	/**
	 * Handles resource conflict exceptions.
	 *
	 * @param ex the thrown exception
	 * @param request the current HTTP request
	 * @return a 409 Conflict response
	 */
	@ExceptionHandler(ConflictException.class)
	public ResponseEntity<ApiError> handleConflict(ConflictException ex, HttpServletRequest request) {
		return buildResponse(HttpStatus.CONFLICT, ex.getMessage(), request, List.of());
	}

	/**
	 * Handles validation failures generated by Bean Validation.
	 *
	 * @param ex the validation exception
	 * @param request the current HTTP request
	 * @return a 400 Bad Request response containing validation details
	 */
	@ExceptionHandler(MethodArgumentNotValidException.class)
	public ResponseEntity<ApiError> handleValidation(
		MethodArgumentNotValidException ex,
		HttpServletRequest request
	) {
		List<String> details = ex.getBindingResult()
			.getFieldErrors()
			.stream()
			.map(this::formatFieldError)
			.collect(Collectors.toList());

		return buildResponse(HttpStatus.BAD_REQUEST, "Validation failed", request, details);
	}

	/**
	 * Handles parameter and binding validation errors.
	 *
	 * @param ex the binding exception
	 * @param request the current HTTP request
	 * @return a 400 Bad Request response containing validation details
	 */
	@ExceptionHandler(BindException.class)
	public ResponseEntity<ApiError> handleBind(BindException ex, HttpServletRequest request) {
		List<String> details = ex.getFieldErrors()
			.stream()
			.map(this::formatFieldError)
			.collect(Collectors.toList());

		return buildResponse(HttpStatus.BAD_REQUEST, "Validation failed", request, details);
	}

	/**
	 * Handles authentication failures.
	 *
	 * @param ex the authentication exception
	 * @param request the current HTTP request
	 * @return a 401 Unauthorized response
	 */
	@ExceptionHandler(AuthenticationException.class)
	public ResponseEntity<ApiError> handleAuthentication(
		AuthenticationException ex,
		HttpServletRequest request
	) {
		return buildResponse(HttpStatus.UNAUTHORIZED, "Authentication failed", request, List.of());
	}

	/**
	 * Handles authorization failures.
	 *
	 * @param ex the access denied exception
	 * @param request the current HTTP request
	 * @return a 403 Forbidden response
	 */
	@ExceptionHandler(AccessDeniedException.class)
	public ResponseEntity<ApiError> handleAccessDenied(
		AccessDeniedException ex,
		HttpServletRequest request
	) {
		return buildResponse(HttpStatus.FORBIDDEN, "Access denied", request, List.of());
	}

	/**
	 * Handles requests targeting non-existing routes or resources.
	 *
	 * @param ex the routing exception
	 * @param request the current HTTP request
	 * @return a 404 Not Found response
	 */
	@ExceptionHandler({ NoResourceFoundException.class, NoHandlerFoundException.class })
	public ResponseEntity<ApiError> handleMissingRoute(
		Exception ex,
		HttpServletRequest request
	) {
		return buildResponse(HttpStatus.NOT_FOUND, "Resource not found", request, List.of());
	}

	/**
	 * Handles unexpected exceptions not covered by more specific handlers.
	 *
	 * @param ex the unexpected exception
	 * @param request the current HTTP request
	 * @return a 500 Internal Server Error response
	 */
	@ExceptionHandler(Exception.class)
	public ResponseEntity<ApiError> handleUnexpected(Exception ex, HttpServletRequest request) {
		return buildResponse(
			HttpStatus.INTERNAL_SERVER_ERROR,
			"Unexpected internal error",
			request,
			List.of()
		);
	}

	/**
	 * Creates a standardized API error response.
	 *
	 * @param status the HTTP status code
	 * @param message the main error message
	 * @param request the originating request
	 * @param details additional error details
	 * @return a response entity containing an {@link ApiError}
	 */
	private ResponseEntity<ApiError> buildResponse(
		HttpStatus status,
		String message,
		HttpServletRequest request,
		List<String> details
	) {
		ApiError body = new ApiError(
			Instant.now(),
			status.value(),
			status.getReasonPhrase(),
			message,
			request.getRequestURI(),
			details
		);
		return ResponseEntity.status(status).body(body);
	}

	/**
	 * Converts a validation error into a human-readable message.
	 *
	 * @param error the validation field error
	 * @return a formatted validation error message
	 */
	private String formatFieldError(FieldError error) {
		return error.getField() + ": " +
			(error.getDefaultMessage() == null
				? "invalid value"
				: error.getDefaultMessage());
	}
}
